### ISSUE TITLE
Pgbackrest restoration issue

### ISSUE THREAD

**Issue by jbreddy** [timescale/timescaledb-docker-ha#120]
Hi Team,

We deployed docker image by using this docker file & testing pgbackrest functionality.

pgbackrest backup all test cases working, But while trying to restore getting this error

postgres@f9135b3f97f3:~$ pgbackrest --stanza=testing --log-level-stderr=info restore
WARN: configuration file contains invalid option 'repo-retention-history'
INFO: restore command begin 2.33: --config=/home/postgres/pgdata/backup/pgbackrest.conf --exec-id=32-17468f89 --log-level-stderr=info --pg1-path=/home/postgres/pgdata/data --repo1-path=/home/postgres/pgdata/backup --stanza=testing
ERROR: [038]: unable to restore while PostgreSQL is running
       HINT: presence of 'postmaster.pid' in '/home/postgres/pgdata/data' indicates PostgreSQL is running.
       HINT: remove 'postmaster.pid' only if PostgreSQL is not running.
INFO: restore command end: aborted with exception [038]

How can we run pgbackrest from host level? 
We are unable to run pgbackrest from host

**Comment by feikesteenbergen** [comment]
What are you trying to achieve and what are the steps that lead up to this error message?
How do you run this Docker Image, what platform (if any) do you use?
Do you use Kubernetes?
Do you run this on AWS/GCP?

**Comment by jbreddy** [comment]
HI @feikesteenbergen 

What are you trying to achieve and what are the steps that lead up to this error message? 

Ans) I'm testing pgbackrest backup & restoration scenarios inside docker. 

As we know we can't restore pgbackrest with stopping PostgreSQL service, But in this we are unable to run pgbackrest  from my EC2 host machine, getting some permission issue, Since we built docker image with some custom UID & GID , In linux host  when we installed PostgreSQL client its creating postgres user with by default UID & GID's.

How do you run this Docker Image, what platform (if any) do you use? 

Ans) We built docker image in Centos 7.8 EC2 instance & deployed docker by using timescaledb-docker-ha docker file.

Do you use Kubernetes?
 
Ans) No we haven't deployed this in Kubernetes & we are not using  Kubernetes 

Do you run this on AWS/GCP?

Ans) We are running this in AWS EC2 machine(Centos 7.8 version).

**Comment by kamilcglr** [comment]
> HI @feikesteenbergen
> 
> What are you trying to achieve and what are the steps that lead up to this error message?
> 
> Ans) I'm testing pgbackrest backup & restoration scenarios inside docker.
> 
> As we know we can't restore pgbackrest with stopping PostgreSQL service, But in this we are unable to run pgbackrest from my EC2 host machine, getting some permission issue, Since we built docker image with some custom UID & GID , In linux host when we installed PostgreSQL client its creating postgres user with by default UID & GID's.
> 
> How do you run this Docker Image, what platform (if any) do you use?
> 
> Ans) We built docker image in Centos 7.8 EC2 instance & deployed docker by using timescaledb-docker-ha docker file.
> 
> Do you use Kubernetes?
> 
> Ans) No we haven't deployed this in Kubernetes & we are not using Kubernetes
> 
> Do you run this on AWS/GCP?
> 
> Ans) We are running this in AWS EC2 machine(Centos 7.8 version).

Hello, did you find a way to restore a backup? We have the same issue.

**Comment by AkashRajvanshi** [comment]
I'm getting the same issue, how can i restore pgbackrest backup on docker container?

**Comment by graveland** [comment]
Generally speaking, we use patroni in this image, and when doing that you can `patronictl pause`, perform the upgrade/restore/whatever you need to do, then `patronictl resume` when you're done. Without patroni, you could stop the container, then run the exact same command, but add `bash` to run a shell instead of the database, and then you'd be inside the container with the same filesystem and utilities allowing you to perform whatever modifications you need.
