### ISSUE TITLE
Extension pg_cron missing from timescale/timescaledb-ha:pg13-ts2.1-latest

### ISSUE THREAD

**Issue by timopulkkinen** [timescale/timescaledb-docker-ha#164]
Pg_cron should be available to be used according to this doc https://kb.timescale.cloud/en/articles/2754991-supported-postgresql-extens

However, it is not listed when checking available extensions. Also, CREATE EXTENSION fails with 

`ERROR:  could not open extension control file "/usr/share/postgresql/13/extension/pg_cron.control": No such file or directory`

**Comment by jflambert** [comment]
I think this PR is potentially incomplete?

pg_cron is not usable unless it is added to `shared_preload_libraries` and postgres restarts.

Was the intent to force those steps on the user, or for `CREATE EXTENSION pg_cron;` work right out of the box? Because right now it doesn't.

**Comment by jflambert** [comment]
new PR #191 would fully fix the issue
