### ISSUE TITLE
Postgres v14 support

### ISSUE THREAD

**Issue by davidandreoletti** [timescale/timescaledb-docker-ha#180]
Hi,

TimescaleDB 2.5 brings support for Postgres 14. Do you plan to support PostgreSQL 14 with 
timescaledb-docker-ha ?

**Comment by davidandreoletti** [comment]
@feikesteenbergen Pinging you :-)

**Comment by jflambert** [comment]
I'd put up a PR but I think it would conflict with this one, which I'm surprised is still open

https://github.com/timescale/timescaledb-docker-ha/pull/175

@feikesteenbergen  please let me know how I can help. I do have a bit of time for this, and I'd love PG14 sooner than later ;)

**Comment by GuanYin108** [comment]
Will there be any updates on pg14.1 support, maybe in conjunction with timescaledb 2.5.1?

**Comment by feikesteenbergen** [comment]
Still need to wait for the Docker Images to be published. That is expected later today ...

**Comment by feikesteenbergen** [comment]
The following images were pushed after surviving CI/CD:

- `timescale/timescaledb-ha:pg14.1-ts2.5.1-p0`
- `timescale/timescaledb-ha:pg14.1-ts2.5.1-oss-p0`

Please not that other than a smoketest, these images have not seen any usage yet. Will give it a spin myself next week.

**Comment by davidandreoletti** [comment]
@feikesteenbergen Super. Thanks. Will report eventual issues too.
