### ISSUE TITLE
upgrade timescaledb-ha:pg13.5-ts2.5.1 to pg14.2-ts2.5.2

### ISSUE THREAD

**Issue by j4ys0n** [timescale/timescaledb-docker-ha#217]
i need to upgrade my timescaledb instasnce to take advantage of some new features in pg14. can i just swap versions in my docker-compose file and restart?

i'm on pg13.5-ts2.5.1 and want to go to pg14.2-ts2.5.2

i did find something about this in the docs but it's with much older versions. i wanted to make sure this still applies.

https://docs.timescale.com/timescaledb/latest/how-to-guides/update-timescaledb/updating-docker/#updating-a-timescaledb-docker-installation

thank you!

**Comment by j4ys0n** [comment]
looks like the answer is no..

```
2022-03-09 20:17:12.117 UTC [1] FATAL:  database files are incompatible with server
2022-03-09 20:17:12.117 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.2 (Ubuntu 14.2-1.pgdg21.04+1).
```

**Comment by feikesteenbergen** [comment]
Moving from PostgreSQL 13 to PostgreSQL 14 requires a `pg_upgrade`. If you pick the `pg14.2-ts2.6.0-p4` image, that contains binaries for PostgreSQL 12, 13 and 14.

However it will be up to you to write a sequence that allows you to execute the `pg_upgrade` successfully. In some of our environments we run an `init` container that does this for us, however I can't really go into details about that as that process is very specific to our situation and not generically useful for this Docker Image.

**Comment by danclimasevschi** [comment]
You could use this project to do the upgrade: https://github.com/tianon/docker-postgres-upgrade

**Comment by graveland** [comment]
Closing since this was answered a long time ago

**Comment by jflambert** [comment]
> Moving from PostgreSQL 13 to PostgreSQL 14 requires a `pg_upgrade`. If you pick the `pg14.2-ts2.6.0-p4` image, that contains binaries for PostgreSQL 12, 13 and 14.

hi @feikesteenbergen I was surprised to read this!

Within the image `timescale/timescaledb-ha:pg14.2-ts2.6.0-p4` I can only find the binaries for 14 (under `/usr/lib/postgresql/` I can only find `14`)

Is there another location where older binaries (for example `initdb`) can be found?
