### ISSUE TITLE
Publish the last supported PG11 version of TS 2.3.1 

### ISSUE THREAD

**Issue by chetananand** [timescale/timescaledb-docker-ha#242]
Hello,
On docker hub, the last released image tag for PG11 is 2.1.1, whereas Timescale can support version 2.3.x as the last supported Timescale version for PG11.

Can we please publish a new image for PG11 including 2.3.1 ?

Thanks,
Chetan

**Comment by graveland** [comment]
We don't build/support pg11 at all anymore
