### ISSUE TITLE
Tests super slow after switching from timescale/timescaledb-postgis:1.4.1-pg11

### ISSUE THREAD

**Issue by mdczaplicki** [timescale/timescaledb-docker-ha#243]
I'm migrating from `timescale/timescaledb-postgis:1.4.1-pg11` to `timescale/timescaledb-ha:pg13-ts2.6-latest` in our project.  
I have an open MR & it's pipelines are now taking ages to complete after switching to new docker image.

Usually full tests step ran for around 18 minutes, now it takes 42 minutes. The only change is docker image for the database service.

Locally tests also take around twice as much as they do with old image.

Have you ever encountered similar behavior?

The configuration for pipelines is super simple:
```
...
  variables:
    POSTGRES_PASSWORD: ...
    POSTGRES_DB: ...
    POSTGRES_USER: ...
  services:
    - name: timescale/timescaledb-ha:pg13-ts2.6-latest
    - name: redis:6.2-alpine
 ```

is there anything I should setup to speed it up?

Part of the logs from local machine:
```
Using postgresql.conf at this path:
/home/postgres/pgdata/data/postgresql.conf

shared_buffers = 3980MB
effective_cache_size = 11940MB
maintenance_work_mem = 1990MB
work_mem = 3396kB
timescaledb.max_background_workers = 8
max_worker_processes = 23
max_parallel_workers_per_gather = 6
max_parallel_workers = 12
wal_buffers = 16MB
min_wal_size = 512MB
default_statistics_target = 500
random_page_cost = 1.1
checkpoint_completion_target = 0.9
max_locks_per_transaction = 128
autovacuum_max_workers = 10
autovacuum_naptime = 10
effective_io_concurrency = 256
timescaledb.last_tuned = '2022-04-29T14:00:49Z'
timescaledb.last_tuned_version = '0.12.0'
Writing backup to:
/tmp/timescaledb_tune.backup202204291400

Recommendations based on 15.55 GB of available memory and 12 CPUs for PostgreSQL 13
Saving changes to: /home/postgres/pgdata/data/postgresql.conf
```

I've also tried to updated configuration & set same values as in previous container, but that didn't change anything.

**Comment by feikesteenbergen** [comment]
Could you share the environments in which you run this? Actual CPU, memory available, as well as a full dump of `postgresql.conf` of both deployments?

**Comment by feikesteenbergen** [comment]
Thanks for the details!
