### ISSUE TITLE
TS_TUNE_MAX_BG_WORKERS variable does nothing

### ISSUE THREAD

**Issue by ilovemysillybanana** [timescale/timescaledb-docker-ha#258]
Documentation for [here](https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/about-configuration/#workers) says we should be able to use either `TS_TUNE_MAX_BG_WORKERS` env var or use the `--max-bg-workers` flag. The flag works but the variable does nothing. 

Version: `timescale/timescaledb-ha:pg13.4-ts2.4.2-p0`

**Comment by jflambert** [comment]
Hi @ilovemysillybanana, could you specify what you mean by "it does nothing"?

Both the flag AND the env var work great for me. I would love to assist if you gave me some replication steps

**Comment by ilovemysillybanana** [comment]
We found a solution, we had to add them to 

```yaml
  timescaledbTune:
    enabled: true
    args:
      max-bg-workers: 5
```
