### ISSUE TITLE
timescale-ha multiarch (ARM/Aarch64) support

### ISSUE THREAD

**Issue by SharkWipf** [timescale/timescaledb-docker-ha#259]
While the main timescaledb image has multiarch support, and attempts have been made (timescale/timescaledb-docker#23, timescale/timescaledb-docker#145) to provide multiarch support for the timescaledb-postgis image, since its deprecation, its recommended replacement, timescaledb-ha, does not offer multiarch support.  
Is there a chance of getting arm/v7 and Aarch64 support on these images?

**Comment by saibotk** [comment]
To give another great reason for this:
This would also make development with timescaledb on ARM-based macs much faster.

Thank you for the amazing software!

**Comment by simonfester** [comment]
+1 for this feature, would allow me to use ARM based EC2 instances - which are cheaper!

**Comment by jason-lindholm** [comment]
+1

**Comment by hexrune** [comment]
just waiting for this

**Comment by amchelmer** [comment]
+1

**Comment by sinsharat** [comment]
Any support planned for this. As i see this issue was raised in May2022.

**Comment by ghstahl** [comment]
It looks like someone is thinking about it. 
https://github.com/timescale/timescaledb-docker-ha/blob/2466f28f5e3ce7c4410b5a1d63f7fab23420c985/Dockerfile#L81

**Comment by sruehl** [comment]
maybe this https://github.com/timescale/timescaledb-docker-ha/pull/355 brings that a bit closer... It contains traces of ARM too :D

**Comment by romulus-ai** [comment]
+1 to may have this amazing software running on arm in the future :)

**Comment by titus-zx** [comment]
+ 1

**Comment by yerffejytnac** [comment]
+1 would love to hear any updates on this

**Comment by sruehl** [comment]
@graveland mentioned in #355 that 

> This also adds most of the required support for arm64 builds as well, but we need to
fix public arm64 build runners before fully building multiplatform images

is there a issue for that to follow? As long as those runners are not fixed I guess there won't be images then.

**Comment by johanatan** [comment]
`+1`

**Comment by maheee** [comment]
Would love to have that as well. I want to run it on a RaspberryPi.

In the meantime, I'm using an image starting with postgres and install timescaledb + toolkit myself:

https://gist.github.com/maheee/309641ce45a511bc61dd12b1eb10c55e

**Comment by tkononowiczsolwit** [comment]
+1 any chance it will work?

**Comment by b-thiswatch** [comment]
if you care for a temporary solution, you could use the dev repository... https://hub.docker.com/u/timescaledev

**Comment by jackson-sandland** [comment]
+1

**Comment by terion-name** [comment]
+1

**Comment by luckylinux** [comment]
I have to do before all of this the following, since I am using Podman, not Docker:
```
ln -s /usr/bin/podman /usr/bin/docker
```

Then it should be about as easy as:
```
git clone https://github.com/timescale/timescaledb-docker-ha.git
PLATFORM="arm64" make build
```

**Comment by wuast94** [comment]
any news on this?

**Comment by liefra** [comment]
> Then it should be about as easy as:
> 
> ```
> git clone https://github.com/timescale/timescaledb-docker-ha.git
> PLATFORM="arm64" make build
> ```
> 
> Seems a bit weird that it's not included in automated builds by default though ...

This worked for me on Mac using Docker

**Comment by Oidlichtnwoada** [comment]
@feikesteenbergen  Could you add the proposed ARM build to your configured CI/CD, this would help timescale adaption ...

**Comment by graveland** [comment]
Should be fixed as of #456

**Comment by Oidlichtnwoada** [comment]
Thank you so much @graveland  @feikesteenbergen

**Comment by manuelvsousa** [comment]
still no linux/arm/v7 officially
