### ISSUE TITLE
Is there a function difference between timescaledev/timescaledb-ha and timescaledev/timescaledb-docker-ha

### ISSUE THREAD

**Issue by TheFutonEng** [timescale/timescaledb-docker-ha#273]
I'm working with an application which currently uses the below container:

[docker.io/timescaledev/timescaledb-ha:pg11.11-ts2.1.0-p1](https://hub.docker.com/layers/timescaledb-ha/timescaledev/timescaledb-ha/pg11.11-ts2.1.0-p1/images/sha256-3f87e96ed6e540d13f15bb2fbcd4d0f454ad7ae5ce30bd18a60397a2492adbac?context=explore)

I need to modify this container slightly and was trying to find it's Dockerfile as a reference.  Googling led me to this repo but just trying to understand what the functional difference is between timescaledev/timescaledb-ha and timescaledev/timescaledb-docker-ha.  Ultimately I want to make sure that I'm making modifications to the correct image via the correct Dockerfile.

Thanks in advance for any help!

**Comment by feikesteenbergen** [comment]
Before we published this image to `timescale/timescaledb-ha`, we experimented with it against ` timescaledev/timescaledb-ha`.
Currently, we don't push to  `timescaledev/timescaledb-ha` anymore.

**Comment by TheFutonEng** [comment]
Thanks for the confirmation @feikesteenbergen.  I'll close the issue with this comment.

**Comment by maurerle** [comment]
Hello,
it seems that images are still pushed to both feeds with different schedule, different sizes and therefore  of course different hashs:

https://hub.docker.com/r/timescaledev/timescaledb-ha/tags?name=pg17.2-ts2.17.2-oss (476MB image size)

vs 

https://hub.docker.com/r/timescale/timescaledb-ha/tags?name=pg17.2-ts2.17.2-oss (760MB imagesize)

What is the difference between these two images? Am I missing documentation somewhere?

**Comment by graveland** [comment]
The timescaledev images are 100% unsupported and only used for testing changes that will eventually end up in the main timescale repository. There is nothing automated that pushes to timescaledev, and it generally shouldn't be used by anybody.
