### ISSUE TITLE
How to add pg_stat_monitor to shared_preload_libraries config?

### ISSUE THREAD

**Issue by 0xkofee** [timescale/timescaledb-docker-ha#287]
I'm trying to turn on the `pg_stats_monitor` but i run into this error:

```
postgres=# CREATE EXTENSION IF NOT EXISTS pg_stat_monitor CASCADE;
postgres=# SELECT application_name, userid AS user_name, datname AS database_name, substr(query,0, 50) AS query, calls, client_ip
           FROM pg_stat_monitor;

ERROR:  pg_stat_monitor: must be loaded via shared_preload_libraries
```
I can't seem to install vi or any text editor in this image to modify `vi /home/postgres/pgdata/data/postgresql.conf` to add `pg_stat_monitor` into `shared_preload_libraries`

**Comment by graveland** [comment]
Generally speaking people use a mount to replace /home/postgres/pgdata/data with a mount to allow data persistence, and edit the file outside of the container. Additionally / alternately, mount /home/postgres/pgdata/data/postgresql.conf (and pg_hba.conf) separately and also modify the file outside of the container.

**Comment by 0xkofee** [comment]
ty this worked
