### ISSUE TITLE
How can I setup timescaledb-ha with patroni??

### ISSUE THREAD

**Issue by AkashRajvanshi** [timescale/timescaledb-docker-ha#288]
Hi, I look for solution to setup timescale db ha with patroni, I also find your custom image with patroni ( pg14.4-ts2.7-patroni-static-primary-latest ), but I can't find any docs or basic cluster setup intro guide. Can you please help me to get the up and running the 3 node timescale db ha cluster. 

- Can we have any getting started guide or any other docs for timescaledb & patroni?
- Can you please drop a link for env variables used in this image?

**Comment by feikesteenbergen** [comment]
This repository only contains the Docker Image.

Documentation on how to run this Docker Image including Patroni  should be sought after in the Patroni project, or when using Kubernetes, you could have a look at the Helm Charts that use Patroni:

- https://patroni.readthedocs.io/en/latest/
- https://github.com/timescale/helm-charts/tree/master/charts/timescaledb-single

**Comment by feikesteenbergen** [comment]
> Can you please drop a link for env variables used in this image?

Why would you need that?

To list environent variables that are set in the image, you can inspect the docker image, for example:

```shell
docker inspect timescale/timescaledb-ha:pg14.5-ts2.7.2-p0
```

trimmed output
```json
[
        "Config": {
            "Env": [
                "PATH=/usr/lib/postgresql/14/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PGROOT=/home/postgres",
                "PGDATA=/home/postgres/pgdata/data",
                "PGLOG=/home/postgres/pg_log",
                "PGSOCKET=/home/postgres/pgdata",
                "BACKUPROOT=/home/postgres/pgdata/backup",
                "PGBACKREST_CONFIG=/home/postgres/pgdata/backup/pgbackrest.conf",
                "PGBACKREST_STANZA=poddb",
                "LC_ALL=C.UTF-8",
                "LANG=C.UTF-8",
                "PAGER="
            ],
    }
]
```
