### ISSUE TITLE
recommended way to enable `pg_stat_statements` on first run?

### ISSUE THREAD

**Issue by fsiler** [timescale/timescaledb-docker-ha#293]
I'm using the `timescale/timescaledb-ha:pg14.4-ts2.7.2-latest` image in a `docker-compose` configuration.  I would really like to run a `pgwatch2` sidecar, but enabling `pg_stat_statements` is proving to be a real headache.  Doing so requires two steps:

- in `postgresql.conf`: `shared_preload_libraries = 'timescaledb,pg_stat_statements'`
- `CREATE EXTENSION pg_stat_statements;`

Would y'all be inclined to accept a patch that would enable defining a `POSTGRES_ENABLE_PG_STAT_STATEMENTS` variable which would modify the behavior of [this line](https://github.com/timescale/timescaledb-docker-ha/blob/dc00bfd484d77a975ba5dcec792b377541159fc8/Dockerfile#L165) and also run a script to enable the extension?

**Comment by jflambert** [comment]
To answer your question, this is how I do it in docker-compose

by no means is this the "recommended way" but it works

![image](https://user-images.githubusercontent.com/11539524/191993519-4f567aa5-67e7-4173-8402-f615daa3e4d9.png)

**Comment by fsiler** [comment]
@jflambert sure, so maybe the solution is to have a second flag, `POSTGRES_ENABLE_PLUGIN_DEBUGGER`, which has analogous functionality.

**Comment by graveland** [comment]
> To answer your question, this is how I do it in docker-compose
> 
> by no means is this the "recommended way" but it works. Except of course you still need to create the extension(s) after the fact, but I have this in a migration step for my application...
> 
> ![image](https://user-images.githubusercontent.com/11539524/191993519-4f567aa5-67e7-4173-8402-f615daa3e4d9.png)

This plus a script file in `/docker-entrypoint-initdb.d/`, so possibly `-v create_extensions.sh:/docker-entrypoint-initdb.d/create_extensions.sh` containing something like:
```sh
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc -c "create extension pg_stat_statements" template1
```

With slight modifications for whatever you're trying to specifically do, it will get you a database that should have the required extensions on first run.
