### ISSUE TITLE
Create guide for PG upgrades (majors and minors)

### ISSUE THREAD

**Issue by manute** [timescale/timescaledb-docker-ha#296]
Part of the effort of updating the postgres minor version to 14.5 task, it will require a guide in slab about how to do that for minors and majors versions, what repos are involved and describing the process in detail.

**Comment by manute** [comment]
https://timescale.slab.com/posts/pg-upgrades-process-04m4lgs7 - any feedback really appreciated

**Comment by wolph** [comment]
I don't seem to have access to the slab thing, but these are roughly the steps I've taken:

1. Stop the previous database server
2. Rename the old `data` directory to `data14`: `mv pgdata/data{,14}`
3. Drop into a docker shell for the upgrade: `docker run --rm -v ./:/home/postgres -ti --entrypoint=/bin/bash timescale/timescaledb-ha:pg15-latest`

From the shell:
```
# Start the old Postgres server with the old data
/usr/lib/postgresql/14/bin/pg_ctl -D /home/postgres/pgdata/data14 start

# Upgrade the extensions
psql -X <database>
alter extension timescaledb update;
alter extension timescaledb_toolkit update;

# Stop the server again
/usr/lib/postgresql/14/bin/pg_ctl -D /home/postgres/pgdata/data14 stop

# Create the new database with the correct locale
initdb -D /home/postgres/pgdata/data --locale=en_US.utf8 --encoding=UTF8
export PGDATAOLD=/home/postgres/pgdata/data14
export PGDATANEW=/home/postgres/pgdata/data
export PGBINOLD=/usr/lib/postgresql/14/bin
export PGBINNEW=/usr/lib/postgresql/15/bin
pg_upgrade --link --verbose
```

4. Update your docker-compose file to use the new version and start it again
