### ISSUE TITLE
any interest in including ZomboDB?

### ISSUE THREAD

**Issue by fsiler** [timescale/timescaledb-docker-ha#303]
Particularly for promscale/trace usage, it seems like full text search could be very valuable.  Was wondering if there's any interest in accepting PRs for ZomboDB, which is Apache licensed.

**Comment by graveland** [comment]
Generally speaking if you create a PR for it and it isn't too intrusive, it would probably be accepted. I don't think we plan on adding that support without community help though!

It's a lot easier if it's already packaged somewhere, as installing rust extensions is a pain and adds a LOT of time to the build!

Closing this as it's old/stale, but feel free to re-open or create a PR!
