### ISSUE TITLE
Function does not exist

### ISSUE THREAD

**Issue by iRakic** [timescale/timescaledb-docker-ha#309]
Hello everyone,

I have installed the latest timescale/timescaledb-ha:pg14-latest Docker image.
When I execute a query I'm getting the following error:
`ERROR:  function first(integer) does not exist
LINE 7:     first(price_ht.price) AS price_first,
            ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
`
Here is the list of installed extensions in Postgres:

> postgres=# \dx
                                                    List of installed extensions
        Name         | Version |   Schema   |                                      Description
---------------------+---------+------------+---------------------------------------------------------------------------------------
 pgcrypto            | 1.3     | public     | cryptographic functions
 plpgsql             | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb         | 2.8.0   | public     | Enables scalable inserts and complex queries for time-series data
 timescaledb_toolkit | 1.10.1  | public     | Library of analytical hyperfunctions, time-series pipelining, and other SQL utilities
(4 rows)

Can you please advise how this can be fixed or is it a bug? 

Thank you in advance!

**Comment by feikesteenbergen** [comment]
the `first` aggregate function requires 2 arguments, it returns 1 column value based upon the ordering of another.

 > For example, first(temperature, time) returns the earliest temperature 

https://docs.timescale.com/api/latest/hyperfunctions/first/
