### ISSUE TITLE
Missing text editor in image. Unable to use patronictl edit-config.

### ISSUE THREAD

**Issue by wayofka** [timescale/timescaledb-docker-ha#321]
Problem:
Some of the cluster settings cannot be updated.

For example:
max_connections
max_locks_per_transaction
max_worker_processes
max_prepared_transactions

Cause:
These settings from bootstrap/dcs section are stored in etcd during cluster init. The changes in the cluster yaml file is not applied (inc. cluster restart), it is necessary to use `patronictl edit-config`, which apply the configuration into etcd ( + cluster restart ). But this is not possible because no editor is available in docker image.

```
podman exec -it timescaledb /bin/bash -c 'patronictl -c /home/postgres/postgres.yml edit-config'
Error: EDITOR environment variable is not set. editor or vi are not available
```
Environment:
Timescaledb + patroni + pgbouncer + etcd + haproxy
Docker image: `timescaledb-ha:pg14.4-ts2.7.2-latest`

Solution:
Add to the docker image text editor, ideally vi.
`RUN apt-get install -y vim`

**Comment by VMM-Mtech** [comment]
At least there's sed. We managed to do something with it. See [this](https://linuxhint.com/use-sed-to-edit-file-in-place/) for some examples.

**Comment by graveland** [comment]
vim-tiny is included for quite a while now
