### ISSUE TITLE
build-oss incorrectly results in using the Timescale license is used instead of apache

### ISSUE THREAD

**Issue by ekondrashev** [timescale/timescaledb-docker-ha#332]
Hi TimescaleDB community!

I'm having hard time building the image using `apache2` license.

I've built the image using `build-oss` argument like below:
```
POSTGIS_VERSIONS="" make build-oss
```

then I launched the container via
```
➜  ~ docker run -e OSS_ONLY=" -DAPACHE_ONLY=1" -e POSTGRES_PASSWORD="12345" -it --name eloquent_benz -it docker.io/library/14-oss-labeled
```

At this point I was expecting that I’m using Apache 2.0 licensed product, but it says that I’m using `timescale` license
```
➜  ~ docker exec -it eloquent_benz psql -c "SHOW timescaledb.license;"                      
 timescaledb.license 
---------------------
 timescale
(1 row)
```

Moreover, I've tried one of the officially available oss images, like
```
docker run -e OSS_ONLY=" -DAPACHE_ONLY=1" -e POSTGRES_PASSWORD="12345" -it --name eloquent_benz -it timescale/timescaledb-ha:pg14.1-ts2.5.1-oss-p0
```
and it seems that this version is still returns `timescale` license
```
➜  ~ docker exec -it eloquent_benz bash -c "echo \$OSS_ONLY"
-DAPACHE_ONLY=1
➜  ~ docker exec -it eloquent_benz psql -c "SHOW timescaledb.license;"
 timescaledb.license 
---------------------
 timescale
(1 row)
```

For the TImescaleDB 2.0.0 built from sources, I was specifying `TIMESCALEDB_APACHE_LICENSE 'ON'` which was forcing to pass ` -DAPACHE_ONLY=ON` to `./bootstrap` command and that was making the SQL query return apache2 license

But why it is not the case for TimescaleDB HA? Am I doing anything wrong here?

I was asking these questions from TimescaleDB Community #timescale-license channel

```
So the questions are
1. Is it expected that oss built image returns non Apache 2.0 license?
2. Is it that latest TimescaleDB will always return timescale by running SHOW timescaledb.license; and it is only my usage of a product features defines a license?
3. Am I still in a risk of falling notn Apache 2.0 usage even when using make build-oss image?
```
And got answers:
```
1. No
2. It should not.
```
https://timescaledb.slack.com/archives/CEY5H4SMQ/p1669902990196039

with a suggestion to post an issue here

**Comment by ekondrashev** [comment]
Created PR that fixes the issue
https://github.com/timescale/timescaledb-docker-ha/pull/333

The license is `apache` now
```
➜  ~ docker exec -it eloquent_benz psql -c "SHOW timescaledb.license;"
 timescaledb.license 
---------------------
 apache
(1 row)

```

**Comment by graveland** [comment]
It should be fixed now if you're running a docker image with `-oss` in the tag name. Moreover, `docker run -e OSS_ONLY=" -DAPACHE_ONLY=1"` isn't expected to change what's running. The `-DAPACHE_ONLY=1` is a build-time argument when building the timescaledb extension, not a run-time argument.

Please double-check and close this issue if it's fixed, thanks!
