### ISSUE TITLE
Cannot use this image with a custom uid/gid and bind-mounts.

### ISSUE THREAD

**Issue by laundmo** [timescale/timescaledb-docker-ha#345]
Docker allows telling a container as which user to run a process, using the `--user 1002:1002` argument or equivalent setting in docker-compose. This is especially important for docker hosts where the default uid/gid (1000:1000) belong to a user who should not have access to the data.

The official postgres docker image documentation suggests that passing this user flag and adding a read-only mapping of the hosts /etc/passwd will allow using a custom user. This does not work in timescale, as timescale has hardcoded the `postgres` user with the uid/gid 1000:1000.
https://github.com/timescale/timescaledb-docker-ha/blob/cc0deb86fcab07c25da7ac90af45ee0ff868ae62/Dockerfile#L39
https://github.com/timescale/timescaledb-docker-ha/blob/cc0deb86fcab07c25da7ac90af45ee0ff868ae62/Dockerfile#L519

Please provide guidance of bind-mounting the pgdata directory as another uid/gid than 1000:1000.

related issues:
- #272

**Comment by graveland** [comment]
Let me know if this works for you!
