### ISSUE TITLE
Does not support the TS_TUNE_* environment variables

### ISSUE THREAD

**Issue by devanubis** [timescale/timescaledb-docker-ha#366]
I was surprised to find that this `-ha` docker image doesn't support `TS_TUNE_MAX_BG_WORKERS` (_reported as #258 but later closed when they found their own workaround_) or any of the other environment variables from the base https://github.com/timescale/timescaledb-docker.

Controlling things like max-workers through environment variables seems like a pretty important option. It would certainly help me prevent a bug in my test environment which deploys an image using the default endpoint and drop-creates new DBs, but is getting locked out of creating those due to background workers on the `template1` (timescale/timescaledb#4048)

I'm looking into workarounds for myself, but environment variables really would be the best option.

**Comment by jflambert** [comment]
Like I asked in the other issue, which version are you running?

**Comment by graveland** [comment]
This is quite old, closing as stale.
