### ISSUE TITLE
TimescaleDB Community container images for PostgreSQL 14.7 are missing

### ISSUE THREAD

**Issue by dankeder** [timescale/timescaledb-docker-ha#367]
It seems that container images of "TSDB Community" for PostgreSQL 14.7 are missing in Docker Hub.

For example:
```sh
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.10.0-latest
Error response from daemon: manifest for timescale/timescaledb-ha:pg14.7-ts2.10.0-latest not found: manifest unknown: manifest unknown
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.9.3-latest
Error response from daemon: manifest for timescale/timescaledb-ha:pg14.7-ts2.9.3-latest not found: manifest unknown: manifest unknown
```

There are OSS images though:

```sh
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.10.0-oss-latest
pg14.7-ts2.10.0-oss-latest: Pulling from timescale/timescaledb-ha
(...)
$ docker pull timescale/timescaledb-ha:pg14.7-ts2.9.3-oss-latest
pg14.7-ts2.9.3-oss-latest: Pulling from timescale/timescaledb-ha
(...)
```

There is also a "TSDB Community" image for PostgreSQL 15.2 (== the latest PostgreSQL):

```sh
$ docker pull timescale/timescaledb-ha:pg15.2-ts2.10.0-latest
pg15.2-ts2.10.0-latest: Pulling from timescale/timescaledb-ha
(...)
```

I don't know whether this is intentional and only the most recent Postgres is supported, but I haven't found any mention of it in the docs. Please if it's possible, can you also build these missing container images for PostgreSQL 14.7?

Thank you.

**Comment by ocZio** [comment]
pinging @feikesteenbergen, had noticed the same while trying to upgrade to 2.10.1

Is there anything we can do to help you with this @feikesteenbergen ?

**Comment by mindrunner** [comment]
https://github.com/timescale/timescaledb-docker-ha/issues/363
