### ISSUE TITLE
Publish compiler image every so often

### ISSUE THREAD

**Issue by feikesteenbergen** [timescale/timescaledb-docker-ha#409]
We have lost the compiler image at some point, however, some other repositories still pull this image to build software.

It would therefore really help to add the compiler image back into this repository.

**Comment by feikesteenbergen** [comment]
I have triggered the (very old) job using a very old commit [here](https://github.com/timescale/timescaledb-docker-ha/actions/runs/5877921475) in order for us to have a compiler image for the current minor PostgreSQL versions. That should help for the next 2 months or so.

**Comment by graveland** [comment]
The compiler image was replaced by the builder version
