### ISSUE TITLE
Add riscv64 support

### ISSUE THREAD

**Issue by anzhi998** [timescale/timescaledb-docker-ha#438]
Hey there,
I attempted cross-compilation using buildx, but encountered numerous dependencies that needed adjustments. Many of these dependencies lacked RISC-V versions available for direct retrieval, requiring compilation from source. Despite my prolonged efforts, I was unable to build the riscv image.
It'd be really cool if this image was published with RISCV64 support.
Thanks!

**Comment by graveland** [comment]
We don't have access to public riscv64 builders, and building this via emulation would take _ages_. Building arm64 via emulation ended up getting cancelled before it was complete by github's maximum job timeout of 6 hours. It would be cool, but I don't think it'll happen without public risc builders becoming available.
