### ISSUE TITLE
Difference between `multi` and `all` tags

### ISSUE THREAD

**Issue by richturner** [timescale/timescaledb-docker-ha#446]
Hi,

We've been using the `pg14-multi` tagged image and tried updating to `pg16-all` as this is multiarch and `pg16-multi` doesn't exist but although it seems to work my flywayDB migration code no longer respects the requested default schema and ultimately breaks our code.

I then tried `pg15-all` and that produced the same issue but then noticed there is a `pg15-multi` so I tried that and it works fine.

Would just like to understand what is different between the `-all` and the `-multi` images because whatever it is it seems to cause issues with multiple schemas and the search path.

**Comment by graveland** [comment]
-multi is an old, and unsupported transition version that included arm64 and amd64 multiplatform images. That should be fixed now, as of #456 we're building arm+amd by default. Please ignore the -multi images and use the regular ones (pg16, pg16-all).
