### ISSUE TITLE
Upgrade pgbouncer to 1.21.x

### ISSUE THREAD

**Issue by matscr** [timescale/timescaledb-docker-ha#451]
Hi!
As of my understanding, timescaledb-ha image is with bgbouncer version 1.20.
We need to have support for prepared statements. This is supposed to be supported in bgbouncer 1.21.0
https://www.postgresql.org/about/news/pgbouncer-1210-released-now-with-prepared-statements-2735/

Hoping that timescaledb-ha image can have its pgbouncer upgraded to 1.21

**Comment by graveland** [comment]
The latest images have pgbouncer 1.22.0, it's picked up automatically from the upstream repositories.
