### ISSUE TITLE
How to build timescaledb-docker-ha image in redhat ubi8 base image

### ISSUE THREAD

**Issue by vijaybhaskar644** [timescale/timescaledb-docker-ha#453]
default base image in the repo is ubuntu, we have requirement to build on redhat ubi8 minimal base image, but the Dockerfile commands not working, can somebody provide steps to build image with Dockerfile using redhat ubi8 base image

**Comment by graveland** [comment]
It would be a huge undertaking to change the base image. All the packaging commands, repositories, versions, ... almost everything would need changing to account for using RH and rpms. I estimate that 75% of the lines in the Dockerfile would need to be changed. There may be other repositories that might be based off of redhat though, but I haven't looked.

**Comment by graveland** [comment]
Do you mean [timescaledb-docker](https://github.com/timescale/timescaledb-docker)? If so, then one of the big differences between the two repositories is that this one builds rust components (like timescaledb-toolkit), and that would be prohibitively slow with emulation. It causes the github actions jobs to timeout after 6 hours, so I don't think that repo would include the toolkit.
