### ISSUE TITLE
Patroni version>=4 don't work

### ISSUE THREAD

**Issue by AbhishPrasad** [timescale/timescaledb-docker-ha#513]
The helm chart works when the version of patroni in docker image is<4 else because of patroni configuration changes this is not working. 
Need to update the chart to support patroni>=4 versions.

**Comment by graveland** [comment]
This repo doesn't have a chart, so please create an issue for whatever chart you're using in the chart's repository. Patroni 4 in this repository works fine, and we have no plans on downgrading here.
