### ISSUE TITLE
Missing ts2.0 tag

### ISSUE THREAD

**Issue by haf** [timescale/timescaledb-docker-ha#76]
There's no pushed imaged that matches the naming standard detailed in the README e.g. `pg12-ts2.0-tsl` https://hub.docker.com/r/timescaledev/timescaledb-ha/tags?page=1&ordering=last_updated&name=latest

The closest to what's pushed is 

<img width="680" alt="image" src="https://user-images.githubusercontent.com/193115/103480719-2d1ac000-4dd6-11eb-9d1e-943cc919cddb.png">

**Comment by feikesteenbergen** [comment]
The latest ones were pushed only yesterday, this image is an immutable image with PostgreSQL 12 and timescale 2.0.0:

timescaledev/timescaledb-ha:pg12.5-ts2.0.0-p0

**Comment by haf** [comment]
Nice
