### ISSUE TITLE
Not drop-in replacement for Spilo in zalando/postgres-operator

### ISSUE THREAD

**Issue by haf** [timescale/timescaledb-docker-ha#77]
When changing the image to `timescaledev/timescaledb-ha:pg12-ts2.0.0-rc4` you get this error message on boot:

```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

**Comment by feikesteenbergen** [comment]
How do you run the Docker image when you get this message?

**Comment by haf** [comment]
I first start the Zalando operator, create a basic database and then switch `docker_image` to yours.

**Comment by kubaracek** [comment]
@haf This obviously won't work. Zalando's operator has its own image preloaded with spilo and other goodies.
Their image has `timescaledb` preinstalled so you're supposed to just enable the extension for you database there. It's already a HA setup

**Comment by haf** [comment]
@kubaracek I think you're wrong on two accounts:

1. Your implied "timescale db's image does not have spilo installed" — https://github.com/timescale/timescaledb-docker-ha/blob/master/Dockerfile#L4 (I don't know about "goodies")
2. HA = failover = clustering. HA is always responding to reads and/or writes. Failover is failing over if one node needs rebooting or crashes. Clustering is splitting up the work across multiple nodes. The reason I want to use the timescale image is that it supports clustering and failover using Spilo. Postgres as such doesn't support high availability, since it's both partition tolerant and consistent.

**Comment by kubaracek** [comment]
Ok I wasn't aware that they try to make this compactible with the operator but the default spilo image https://github.com/zalando/spilo that zalando-operator uses by default supports clustering and failover :shrug:

**Comment by kubaracek** [comment]
I wasn't aware this image tries to be compactible with the operator. Anyway https://github.com/zalando/spilo is the image that zalando-operator uses by default

**Comment by kubaracek** [comment]
I wasn't aware this repo tries to be compatible with zalando operator. 
Anyway, thanks for the schooling for what HA is I now finally understand what that means (:
